Not working due to compatibility issues, likely due to rest_auth and Django 4.
